name: Build and Push to Artifact Registry

on:
  push:
    branches: ["main"]

env:
  PROJECT_ID: beckerlabs
  REGION: us-central1
  GAR_LOCATION: us-central1-docker.pkg.dev/beckerlabs/registry/portfolio

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: Get Version
        id: get_version
        run: |
          echo "VERSION=$(head -n 1 CHANGELOG.md | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')" >> $GITHUB_ENV

      - name: "Output version"
        run: |
          echo "${{ env.VERSION }}"

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ env.GAR_LOCATION }}:${{ env.VERSION }} --build-arg VERSION=${{ env.VERSION }}

      - name: Push image
        run: docker push ${{ env.GAR_LOCATION }}:${{ env.VERSION }}

      - name: Deploy
        run: |
          gcloud run deploy portfolio \
          --region ${{ env.REGION }} \
          --image ${{ env.GAR_LOCATION }}:${{ env.VERSION }} \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ env.PROJECT_ID }} 